#eureka:
#  instance:
#    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
#    hostname: eureka-server3
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://172.31.31.10:1111/eureka/, http://172.31.31.11:1111/eureka/
