eureka:
  instance:
#    instance-id: ${spring.application.name}:${spring.cloud.client.ip_address}:${server.port}
#    hostname: eureka.xrlj.com
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://172.31.94.241:1111/eureka/
