eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}:${server.port}
    hostname: eureka-server2
  client:
    service-url:
      defaultZone: http://eureka-server1:${server.port}/eureka/,http://eureka-server3:${server.port}/eureka/ #做集群
