eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip_address}:${server.port}
#    hostname: eureka-server1.xrlj.com
  client:
    fetch-registry: false
    register-with-eureka: false  #不注册自己
    service-url:
      defaultZone: http://172.31.31.31:1111/eureka/
  server:
      enable-self-preservation: false #设为false，关闭自我保护
      eviction-interval-timer-in-ms: 4000  # 清理间隔（单位毫秒，默认是60*1000）

