eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    hostname: 192.168.10.111
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
