eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    hostname: eureka-server1
  client:
    service-url:
      defaultZone:  http://eureka-server2:${server.port}/eureka/,http://eureka-server3:${server.port}/eureka/
