server:
  port: 1111
spring:
  application:
    name: eureka-server
  profiles:
    active: dev
logging:
  level:
    com:
      netflix:
        eureka: off
        discovery: off
  file: logs/${spring.application.name}.log
