server:
  port: 2222
eureka:
  instance:
    hostname: eureka-server1
  client:
    service-url:
      defaultZone: http://eureka-server1:${server.port}/eureka/,http://eureka-server2:${server.port}/eureka/ #做集群