eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip_address}:${server.port}
#    hostname: eureka-server1.xrlj.com
  client:
    fetch-registry: false # 此客户端是否获取eureka服务器注册表上的注册信息，默认为true
    register-with-eureka: false  #不注册自己,实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true
    service-url:
      defaultZone: http://localhost:1111/eureka/
  server:
      enable-self-preservation: false #设为false，关闭自我保护
      eviction-interval-timer-in-ms: 4000  # 清理间隔（单位毫秒，默认是60*1000）

